// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9L2TVjwqvd342KdhDGX_ueWtU_saiSI',
    appId: '1:572126760838:web:paramount-web-app',
    messagingSenderId: '572126760838',
    projectId: 'paramountclasses-78104',
    authDomain: 'paramountclasses-78104.firebaseapp.com',
    storageBucket: 'paramountclasses-78104.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU9L2TVjwqvd342KdhDGX_ueWtU_saiSI',
    appId: '1:572126760838:android:5415826b61c227b28de607',
    messagingSenderId: '572126760838',
    projectId: 'paramountclasses-78104',
    storageBucket: 'paramountclasses-78104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9L2TVjwqvd342KdhDGX_ueWtU_saiSI',
    appId: '1:572126760838:ios:paramount-ios-app',
    messagingSenderId: '572126760838',
    projectId: 'paramountclasses-78104',
    storageBucket: 'paramountclasses-78104.firebasestorage.app',
    iosBundleId: 'com.example.paramount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU9L2TVjwqvd342KdhDGX_ueWtU_saiSI',
    appId: '1:572126760838:ios:paramount-macos-app',
    messagingSenderId: '572126760838',
    projectId: 'paramountclasses-78104',
    storageBucket: 'paramountclasses-78104.firebasestorage.app',
    iosBundleId: 'com.example.paramount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU9L2TVjwqvd342KdhDGX_ueWtU_saiSI',
    appId: '1:572126760838:web:paramount-windows-app',
    messagingSenderId: '572126760838',
    projectId: 'paramountclasses-78104',
    authDomain: 'paramountclasses-78104.firebaseapp.com',
    storageBucket: 'paramountclasses-78104.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );
}